version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: ${DB_DATABASE}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DOCKER_PORT}:${DB_PORT}"

volumes:
  postgres:
    name: ${DB_DATABASE}