version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: ${DB_DATABASE}
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DOCKER_PORT}:${DB_PORT}"

volumes:
  mysql-data:
    name: ${DB_DATABASE}